# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - name: Install ADMIXTOOLS dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install perl libopenblas-dev libgsl-dev liblapack-dev

      - name: Install ADMIXTOOLS dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install openblas gsl lapack

      - name: Compile and install ADMIXTOOLS (Linux + macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p ~/deps
          cd ~/deps
          curl -LO https://github.com/DReichLab/AdmixTools/archive/v7.0.2.tar.gz
          tar xf v7.0.2.tar.gz
          cd AdmixTools-7.0.2
          cd src
          make clobber
          export LDFLAGS="-L/usr/local/opt/openblas/lib"
          export CPPFLAGS="-I/usr/local/opt/openblas/include"
          make LDLIBS="-llapack" all
          make install
          cd ../
          curl -LO https://reich.hms.harvard.edu/sites/reich.hms.harvard.edu/files/inline-files/AdmixTools_Example_Data.tar_.gz
          tar xf AdmixTools_Example_Data.tar_.gz
          cd examples
          # fix unportable Perl shebang
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "1s/.*/\#\!\/usr\/bin\/env perl -w/" mklog
          else
            sed -i "1s/.*/\#\!\/usr\/bin\/env perl -w/" mklog
          fi
          ./mklog
          cd ../
          export PATH=$PATH:$PWD/bin
        shell: bash

      - name: Compile and install SLiM
        if: runner.os != 'Windows'
        run: |
          # download SLiM into a separate directory to avoid CRAN errors
          mkdir -p ~/deps
          cd ~/deps

          # installation instructions copied from the SLiM manual:
          wget http://benhaller.com/slim/SLiM.zip
          unzip SLiM.zip
          cd SLiM
          cmake .
          make slim
          # make sure slendr will be able to find SLiM in the $PATH
          export PATH=$PWD:$PATH
          echo "PATH=$PATH" > ~/.Renviron

      - name: Setup dedicated Python environment for slendr
        if: runner.os != 'Windows'
        run: |
          mkdir ~/R_LIBS
          echo "R_LIBS_USER=~/R_LIBS" >> ~/.Renviron
          R -e 'install.packages("reticulate", repos = "http://cran.rstudio.com")'
          R -e 'reticulate::conda_create(packages = c("msprime=1.1.0", "tskit=0.4.1", "pyslim=0.700", "pandas=1.3.5"), envname = "automatic_slendr_python_env")'

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v1
